services:
  - type: web
    name: bufferring-org-website
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    routes:
      - type: rewrite
        source: /projects
        destination: /index.html
      - type: rewrite
        source: /contact
        destination: /index.html
      - type: rewrite
        source: /*
        destination: /index.html
